import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

import ProfileComponent from "@/components/ProfileCard";
import logo from "@assets/hopshop_logo.svg";

import "./globals.css";

const inter = Montserrat({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='p-4'>
          <div className='flex justify-between items-center mb-5'>
            <Image src={logo.src} width={95} height={15} alt='hop shop' />
            <Link className='text-brand-blue-light font-medium' href='/create'>
              Create Shop
            </Link>
          </div>
          <ProfileComponent username='placeholder' imageSrc='https://via.placeholder.com/150' />
        </header>
        <main className='p-4 pt-0'>{children}</main>
      </body>
    </html>
  );
}
